# Brazilian E-Commerce Public Dataset by Olist

**D3TOP – TÓPICOS EM CIÊNCIAS DE DADOS**<br />
Especialização em Ciência de Dados - IFSP Campinas

Aluno
- Daniel Vargas Shimamoto

# 0. Informações Gerais

## 0.1. Conhecendo  o dataset

<div>
<img src="../images/DataSchema.png" width="600"/>
</div>

Fonte: <a href="https://www.kaggle.com/datasets/olistbr/brazilian-ecommerce">Kaggle</a>

## 0.2. Atributos

# 1. Importações

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
review  = pd.read_csv('../datasets/olist_order_reviews_dataset.csv')
item    = pd.read_csv('../datasets/olist_order_items_dataset.csv')
product = pd.read_csv('../datasets/olist_products_dataset.csv')

review.head(3)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24

In [3]:
item.head(3)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

In [4]:
product.head(3)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0

In [5]:
review_pre = review.dropna(subset = ['review_comment_message'])
review_pre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 40977 entries, 3 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                40977 non-null  object
 1   order_id                 40977 non-null  object
 2   review_score             40977 non-null  int64
 3   review_comment_title     9839 non-null   object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     40977 non-null  object
 6   review_answer_timestamp  40977 non-null  object
dtypes: int64(1), object(6)
memory usage: 2.5+ MB

In [6]:
df = review_pre.merge(item, how = 'left', on = 'order_id').merge(product, how = 'left', on = 'product_id')
df.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,order_item_id,product_id,seller_id,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,1.0,52c80cedd4e90108bf4fa6a206ef6b03,a1043bafd471dff536d0c462352beb48,...,179.99,42.85,ferramentas_jardim,33.0,2188.0,2.0,7650.0,20.0,20.0,20.0
1,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,1.0,3880d25d502b15b1de6fddc42ad1d67a,989becdce12ebc39863c2bceab6f3ca1,...,1199.00,134.25,esporte_lazer,48.0,562.0,5.0,9850.0,105.0,35.0,50.0
2,8670d52e15e00043ae7de4c01cc2fe06,b9bf720beb4ab3728760088589c62129,4,recomendo,aparelho eficiente. no site a marca do aparelh...,2018-05-22 00:00:00,2018-05-23 16:45:47,1.0,61a4100ccd6d9c4c808a1fd954ddb8ad,05ff92fedb5be47920fea08e501238b9,...,586.56,26.69,eletroportateis,60.0,3839.0,4.0,1450.0,24.0,24.0,24.0
3,4b49719c8a200003f700d3d986ea1a19,9d6f15f95d01e79bd1349cc208361f09,4,NaN,"Mas um pouco ,travando...pelo valor ta Boa.\r\n",2018-02-16 00:00:00,2018-02-20 10:52:22,1.0,acffe5d7cd56e6b564cf6841486644ff,db4350fd57ae30082dec7acbaacc17f9,...,35.00,7.78,beleza_saude,58.0,356.0,1.0,200.0,19.0,4.0,11.0
4,3948b09f7c818e2d86c9a546758b2335,e51478e7e277a83743b6f9991dbfa3fb,5,Super recomendo,"Vendedor confiável, produto ok e entrega antes...",2018-05-23 00:00:00,2018-05-24 03:00:01,1.0,6871a3c157d6f51697e887f3c3598479,974cf2cb8f4b7add98709c30df02fe10,...,89.99,13.07,informatica_acessorios,58.0,1923.0,4.0,850.0,25.0,11.0,15.0

In [7]:
df.drop_duplicates(subset = ['order_id','product_category_name'], inplace = True)
df.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,order_item_id,product_id,seller_id,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06,1.0,52c80cedd4e90108bf4fa6a206ef6b03,a1043bafd471dff536d0c462352beb48,...,179.99,42.85,ferramentas_jardim,33.0,2188.0,2.0,7650.0,20.0,20.0,20.0
1,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53,1.0,3880d25d502b15b1de6fddc42ad1d67a,989becdce12ebc39863c2bceab6f3ca1,...,1199.00,134.25,esporte_lazer,48.0,562.0,5.0,9850.0,105.0,35.0,50.0
2,8670d52e15e00043ae7de4c01cc2fe06,b9bf720beb4ab3728760088589c62129,4,recomendo,aparelho eficiente. no site a marca do aparelh...,2018-05-22 00:00:00,2018-05-23 16:45:47,1.0,61a4100ccd6d9c4c808a1fd954ddb8ad,05ff92fedb5be47920fea08e501238b9,...,586.56,26.69,eletroportateis,60.0,3839.0,4.0,1450.0,24.0,24.0,24.0
3,4b49719c8a200003f700d3d986ea1a19,9d6f15f95d01e79bd1349cc208361f09,4,NaN,"Mas um pouco ,travando...pelo valor ta Boa.\r\n",2018-02-16 00:00:00,2018-02-20 10:52:22,1.0,acffe5d7cd56e6b564cf6841486644ff,db4350fd57ae30082dec7acbaacc17f9,...,35.00,7.78,beleza_saude,58.0,356.0,1.0,200.0,19.0,4.0,11.0
4,3948b09f7c818e2d86c9a546758b2335,e51478e7e277a83743b6f9991dbfa3fb,5,Super recomendo,"Vendedor confiável, produto ok e entrega antes...",2018-05-23 00:00:00,2018-05-24 03:00:01,1.0,6871a3c157d6f51697e887f3c3598479,974cf2cb8f4b7add98709c30df02fe10,...,89.99,13.07,informatica_acessorios,58.0,1923.0,4.0,850.0,25.0,11.0,15.0

In [8]:
df.drop(labels = ['review_id', 'review_creation_date','review_answer_timestamp', 'order_item_id', 'seller_id',
       'shipping_limit_date', 'product_name_lenght','product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'], axis = 1, inplace = True)
df.head(3)

,order_id,review_score,review_comment_title,review_comment_message,product_id,price,freight_value,product_category_name
0,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,52c80cedd4e90108bf4fa6a206ef6b03,179.99,42.85,ferramentas_jardim
1,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,3880d25d502b15b1de6fddc42ad1d67a,1199.00,134.25,esporte_lazer
2,b9bf720beb4ab3728760088589c62129,4,recomendo,aparelho eficiente. no site a marca do aparelh...,61a4100ccd6d9c4c808a1fd954ddb8ad,586.56,26.69,eletroportateis

In [9]:
csat = {1:0,2:0,3:0,4:1,5:1}

df.review_score = df.review_score.map(csat)
df.head(3)

,order_id,review_score,review_comment_title,review_comment_message,product_id,price,freight_value,product_category_name
0,658677c97b385a9be170737859d3511b,1,NaN,Recebi bem antes do prazo estipulado.,52c80cedd4e90108bf4fa6a206ef6b03,179.99,42.85,ferramentas_jardim
1,8e6bfb81e283fa7e4f11123a3fb894f1,1,NaN,Parabéns lojas lannister adorei comprar pela I...,3880d25d502b15b1de6fddc42ad1d67a,1199.00,134.25,esporte_lazer
2,b9bf720beb4ab3728760088589c62129,1,recomendo,aparelho eficiente. no site a marca do aparelh...,61a4100ccd6d9c4c808a1fd954ddb8ad,586.56,26.69,eletroportateis

In [10]:
df.product_category_name.value_counts()

cama_mesa_banho                  4291
beleza_saude                     3347
esporte_lazer                    2955
informatica_acessorios           2723
moveis_decoracao                 2592
                                 ...
cds_dvds_musicais                   5
la_cuisine                          5
seguros_e_servicos                  2
pc_gamer                            2
fashion_roupa_infanto_juvenil       1
Name: product_category_name, Length: 73, dtype: int64

In [11]:
df[~df.review_comment_title.isnull()]

,order_id,review_score,review_comment_title,review_comment_message,product_id,price,freight_value,product_category_name
2,b9bf720beb4ab3728760088589c62129,1,recomendo,aparelho eficiente. no site a marca do aparelh...,61a4100ccd6d9c4c808a1fd954ddb8ad,586.56,26.69,eletroportateis
4,e51478e7e277a83743b6f9991dbfa3fb,1,Super recomendo,"Vendedor confiável, produto ok e entrega antes...",6871a3c157d6f51697e887f3c3598479,89.99,13.07,informatica_acessorios
6,583174fbe37d3d5f0d6661be3aad1786,0,Não chegou meu produto,Péssimo,55a1e3d39ace9c0b217f6c30b04d43c0,89.90,9.38,malas_acessorios
7,4fc44d78867142c627497b60a7e0228a,1,Ótimo,Loja nota 10,c56ecdd06c754c22fc5c5245d9502e30,51.67,13.57,beleza_saude
13,37e7875cdce5a9e5b3a692971f370151,1,Muito bom.,Recebi exatamente o que esperava. As demais en...,a76bb75d78ce6aa4a5202051b4f88a83,34.90,22.06,esporte_lazer
...,...,...,...,...,...,...,...,...
48148,16cbf959cfdb88c47ee2a29303547ec2,1,Nota máxima!,"Muito obrigado,\r\n\r\nExcelente atendimento,b...",7192c6fea73bae6687d1b584a551376f,121.00,20.58,relogios_presentes
48150,bd78f91afbb1ecbc6124974c5e813043,1,👍,Aprovado!,3beef4346c92eb0b4ad0b7d025dfe15b,46.90,13.91,cama_mesa_banho
48151,0ebf8e35b9807ee2d717922d5663ccdb,1,muito bom produto,"Ficamos muito satisfeitos com o produto, atend...",fc43d4931ce7b45c01dcf5289927dc01,249.90,20.94,papelaria
48152,b7467ae483dbe956fe9acdf0b1e6e3f4,0,Não foi entregue o pedido,Bom dia \r\nDas 6 unidades compradas só recebi...,a62e25e09e05e6faf31d90c6ec1aa3d1,105.00,11.62,relogios_presentes
48158,f2d12dd37eaef72ed7b1186b2edefbcd,0,Foto enganosa,Foto muito diferente principalmente a graninha...,6adab229374835b551f6402e0dc53267,48.90,7.87,pet_shop